#' Parse sample ID from path to OCTExplorer files
#'
#' Parses the sample ID from the path generated by OCTExplorer.
#'
#' @export
#' @importFrom magrittr %>%
get_sample_id <- function(x) {
  # Get the directory name just up from the XML file.
  # This will be the OCT file base that I use as a sample_id
  dirname(path = x) %>%
    basename() %>%
    return()
}
